### ISSUE TITLE
I can't build hyprfocus using hyprpm

### ISSUE THREAD

**Issue by logexp1** [VortexCoyote/hyprfocus#21]
Here's output of `hyprpm add https://github.com/hyprwm/hyprland-plugins`
```
✔ adding a new plugin repository from https://github.com/hyprwm/hyprland-plugins
  MAKE SURE that you trust the authors. DO NOT install random plugins without verifying the code and author.
  Are you sure? [Y/n]

! old plugin repo build files found in temp directory, removing.
 → Cloning https://github.com/hyprwm/hyprland-plugins
✔ cloned
✔ found hyprpm manifest
✔ parsed manifest, found 6 plugins:
 → borders-plus-plus by Vaxry version
 → csgo-vulkan-fix by Vaxry version
 → hyprbars by Vaxry version
 → hyprexpo by Vaxry version
 → hyprtrails by Vaxry version
 → hyprwinwrap by Vaxry version
 → Manifest has 8 pins, checking
✔ commit pin e45066d0741a1a4b9298a4c5ec43a5e57b059a4e matched hl, resetting
✔ Hyprland headers OK
 → Building borders-plus-plus
✔ built borders-plus-plus into borders-plus-plus/borders-plus-plus.so
 → Building csgo-vulkan-fix
✔ built csgo-vulkan-fix into csgo-vulkan-fix/csgo-vulkan-fix.so
 → Building hyprbars
✔ built hyprbars into hyprbars/hyprbars.so
 → Building hyprexpo
✖ Plugin hyprexpo failed to build.

 → Building hyprtrails
✔ built hyprtrails into hyprtrails/hyprtrails.so
 → Building hyprwinwrap
✔ built hyprwinwrap into hyprwinwrap/hyprwinwrap.so
✔ all plugins built
✔ installed repository
✔ you can now enable the plugin(s) with hyprpm enable
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Done!
```

and I did not give where it went wrong, so in order to do it again with -v option, I removed hyprfocus. But when I try to add again, it says repository already installed.  - `Could not clone the plugin repository. Repository already installed.`

When I `hyprpm list` hyprfocus does not show up.
```
 → Repository hyprland-plugins:
  │ Plugin borders-plus-plus
  └─ enabled: false
  │ Plugin csgo-vulkan-fix
  └─ enabled: false
  │ Plugin hyprbars
  └─ enabled: false
  │ Plugin hyprexpo
  └─ enabled: Plugin failed to build
  │ Plugin hyprtrails
  └─ enabled: false
  │ Plugin hyprwinwrap
  └─ enabled: false
```

How can I resolve the issue? Thanks

**Comment by daxisunder** [comment]
This version is old, it doesn't work with newer Hyprland versions. Use the @pyt0xic fork. What version of Hyprland do you use? `hyprctl version` If it's older than 0.38.0 it won't work since there was a change in Hyprland `header` location in the latest version so, you need to update Hyprland. If you do use 0.38.0:
`hyprpm remove https://github.com/VortexCoyote/hyprfocus`
`hyprpm update`
`hyprpm add https://github.com/pyt0xic/hyprfocus -v`
`hyprpm enable hyprfocus`
If it still doesn't work please, post the output of `hyprpm add https://github.com/pyt0xic/hyprfocus -v`
Also, you can add `exec-once = hyprpm reload -n` to your Hyprland .config to ensure plugin load at start up. `-n` shows notification if there's an error.

**Comment by logexp1** [comment]
Version was 0.38.0. I followed your steps and it works this time.
Thanks!
